### ISSUE TITLE
Issue #1 : Implement Kubernetes for Deployment

### ISSUE THREAD

**Issue by Rapter1990** [Rapter1990/flightsearchapi#1]
**Description:**

- **Task:** Set up Kubernetes for deploying the `FlightSearchAPI` application using Minikube. This will provide container orchestration, scaling, and management of the application in a development or production environment.

---

### **Steps to Complete:**

1. **Install Minikube:**
   - Follow the [[official Minikube installation guide](https://minikube.sigs.k8s.io/docs/start/)](https://minikube.sigs.k8s.io/docs/start/) to install Minikube on your local machine.
   - Ensure you have a compatible hypervisor installed (e.g., Docker, VirtualBox, or HyperKit).

2. **Start Minikube:**
   - Start a Minikube cluster by running:
     ```bash
     minikube start
     ```

3. **Create Kubernetes Deployment Configuration:**
   - Define a deployment YAML file for the `FlightSearchAPI` application to specify the container image, replicas, and resource configurations.

   **Sample Deployment YAML:**
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: flightsearchapi
     labels:
       app: flightsearchapi
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: flightsearchapi
     template:
       metadata:
         labels:
           app: flightsearchapi
       spec:
         containers:
           - name: flightsearchapi
             image: your-username/flightsearchapi:latest
             ports:
               - containerPort: 1133
             env:
               - name: SPRING_DATA_MONGODB_HOST
                 value: "mongodb-service"
               - name: SPRING_DATA_MONGODB_PORT
                 value: "27017"
               - name: SPRING_DATA_MONGODB_DATABASE
                 value: "flightdatabase"
   ```

4. **Create Kubernetes Service Configuration:**
   - Define a service YAML file to expose the `FlightSearchAPI` application for internal or external access.

   **Sample Service YAML:**
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: flightsearchapi-service
   spec:
     type: NodePort
     ports:
       - port: 1133
         targetPort: 1133
         nodePort: 31133
     selector:
       app: flightsearchapi
   ```

5. **Set Up MongoDB Deployment and Service:**
   - Define separate YAML files for MongoDB deployment and service.

   **Sample MongoDB Deployment YAML:**
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: mongodb
     labels:
       app: mongodb
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: mongodb
     template:
       metadata:
         labels:
           app: mongodb
       spec:
         containers:
           - name: mongodb
             image: mongo:latest
             ports:
               - containerPort: 27017
   ```

   **Sample MongoDB Service YAML:**
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: mongodb-service
   spec:
     ports:
       - port: 27017
         targetPort: 27017
     selector:
       app: mongodb
   ```

6. **Set Up Prometheus and Grafana (Optional):**
   - Define deployment and service YAML files for Prometheus and Grafana for monitoring the `FlightSearchAPI` application.
   - Configure Prometheus to scrape metrics from the application and MongoDB.

7. **Test the Kubernetes Deployment:**
   - Apply the configurations:
     ```bash
     kubectl apply -f deployment.yaml
     kubectl apply -f service.yaml
     ```
   - Verify the deployments are running by checking the pods:
     ```bash
     kubectl get pods
     ```
   - Access the `FlightSearchAPI` service using:
     ```bash
     minikube service flightsearchapi-service
     ```

8. **Update Documentation:**
   - Document the steps for deploying the `FlightSearchAPI` application on Kubernetes, including details about environment variables, MongoDB configuration, and monitoring setup.

---

### **Acceptance Criteria:**

- The `FlightSearchAPI` application and MongoDB are deployed and accessible in the Minikube cluster.
- Kubernetes service configurations expose the application correctly.
- Monitoring tools like Prometheus and Grafana are set up (if applicable).
- Documentation is updated to reflect the Kubernetes setup process.
